/// <reference types="expo/types" />

// NOTE: This file should not be edited and is autogenerated by Expo's CLI on
// `expo start` / `expo prebuild`. Committed so type-checking passes before the
// first dev run.
