//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from './schema';
import type {
  FindManyArgs as $FindManyArgs,
  FindUniqueArgs as $FindUniqueArgs,
  FindFirstArgs as $FindFirstArgs,
  ExistsArgs as $ExistsArgs,
  CreateArgs as $CreateArgs,
  CreateManyArgs as $CreateManyArgs,
  CreateManyAndReturnArgs as $CreateManyAndReturnArgs,
  UpdateArgs as $UpdateArgs,
  UpdateManyArgs as $UpdateManyArgs,
  UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs,
  UpsertArgs as $UpsertArgs,
  DeleteArgs as $DeleteArgs,
  DeleteManyArgs as $DeleteManyArgs,
  CountArgs as $CountArgs,
  AggregateArgs as $AggregateArgs,
  GroupByArgs as $GroupByArgs,
  WhereInput as $WhereInput,
  SelectInput as $SelectInput,
  IncludeInput as $IncludeInput,
  OmitInput as $OmitInput,
  UncheckedCreateInput as $UncheckedCreateInput,
  CheckedCreateInput as $CheckedCreateInput,
  UncheckedUpdateInput as $UncheckedUpdateInput,
  CheckedUpdateInput as $CheckedUpdateInput,
  QueryOptions as $QueryOptions,
} from '@zenstackhq/orm';
import type {
  SimplifiedPlainResult as $Result,
  SelectIncludeOmit as $SelectIncludeOmit,
} from '@zenstackhq/orm';
export type UserFindManyArgs = $FindManyArgs<$Schema, 'User'>;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, 'User'>;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, 'User'>;
export type UserExistsArgs = $ExistsArgs<$Schema, 'User'>;
export type UserCreateArgs = $CreateArgs<$Schema, 'User'>;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, 'User'>;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpdateArgs = $UpdateArgs<$Schema, 'User'>;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, 'User'>;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'User'>;
export type UserUpsertArgs = $UpsertArgs<$Schema, 'User'>;
export type UserDeleteArgs = $DeleteArgs<$Schema, 'User'>;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, 'User'>;
export type UserCountArgs = $CountArgs<$Schema, 'User'>;
export type UserAggregateArgs = $AggregateArgs<$Schema, 'User'>;
export type UserGroupByArgs = $GroupByArgs<$Schema, 'User'>;
export type UserWhereInput = $WhereInput<$Schema, 'User'>;
export type UserSelect = $SelectInput<$Schema, 'User'>;
export type UserInclude = $IncludeInput<$Schema, 'User'>;
export type UserOmit = $OmitInput<$Schema, 'User'>;
export type UserUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'User'>;
export type UserCheckedCreateInput = $CheckedCreateInput<$Schema, 'User'>;
export type UserUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'User'>;
export type UserCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'User'>;
export type UserGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'User', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'User', Args, Options>;
export type SessionFindManyArgs = $FindManyArgs<$Schema, 'Session'>;
export type SessionFindUniqueArgs = $FindUniqueArgs<$Schema, 'Session'>;
export type SessionFindFirstArgs = $FindFirstArgs<$Schema, 'Session'>;
export type SessionExistsArgs = $ExistsArgs<$Schema, 'Session'>;
export type SessionCreateArgs = $CreateArgs<$Schema, 'Session'>;
export type SessionCreateManyArgs = $CreateManyArgs<$Schema, 'Session'>;
export type SessionCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Session'>;
export type SessionUpdateArgs = $UpdateArgs<$Schema, 'Session'>;
export type SessionUpdateManyArgs = $UpdateManyArgs<$Schema, 'Session'>;
export type SessionUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Session'>;
export type SessionUpsertArgs = $UpsertArgs<$Schema, 'Session'>;
export type SessionDeleteArgs = $DeleteArgs<$Schema, 'Session'>;
export type SessionDeleteManyArgs = $DeleteManyArgs<$Schema, 'Session'>;
export type SessionCountArgs = $CountArgs<$Schema, 'Session'>;
export type SessionAggregateArgs = $AggregateArgs<$Schema, 'Session'>;
export type SessionGroupByArgs = $GroupByArgs<$Schema, 'Session'>;
export type SessionWhereInput = $WhereInput<$Schema, 'Session'>;
export type SessionSelect = $SelectInput<$Schema, 'Session'>;
export type SessionInclude = $IncludeInput<$Schema, 'Session'>;
export type SessionOmit = $OmitInput<$Schema, 'Session'>;
export type SessionUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Session'>;
export type SessionCheckedCreateInput = $CheckedCreateInput<$Schema, 'Session'>;
export type SessionUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Session'>;
export type SessionCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Session'>;
export type SessionGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Session', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Session', Args, Options>;
export type AccountFindManyArgs = $FindManyArgs<$Schema, 'Account'>;
export type AccountFindUniqueArgs = $FindUniqueArgs<$Schema, 'Account'>;
export type AccountFindFirstArgs = $FindFirstArgs<$Schema, 'Account'>;
export type AccountExistsArgs = $ExistsArgs<$Schema, 'Account'>;
export type AccountCreateArgs = $CreateArgs<$Schema, 'Account'>;
export type AccountCreateManyArgs = $CreateManyArgs<$Schema, 'Account'>;
export type AccountCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Account'>;
export type AccountUpdateArgs = $UpdateArgs<$Schema, 'Account'>;
export type AccountUpdateManyArgs = $UpdateManyArgs<$Schema, 'Account'>;
export type AccountUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Account'>;
export type AccountUpsertArgs = $UpsertArgs<$Schema, 'Account'>;
export type AccountDeleteArgs = $DeleteArgs<$Schema, 'Account'>;
export type AccountDeleteManyArgs = $DeleteManyArgs<$Schema, 'Account'>;
export type AccountCountArgs = $CountArgs<$Schema, 'Account'>;
export type AccountAggregateArgs = $AggregateArgs<$Schema, 'Account'>;
export type AccountGroupByArgs = $GroupByArgs<$Schema, 'Account'>;
export type AccountWhereInput = $WhereInput<$Schema, 'Account'>;
export type AccountSelect = $SelectInput<$Schema, 'Account'>;
export type AccountInclude = $IncludeInput<$Schema, 'Account'>;
export type AccountOmit = $OmitInput<$Schema, 'Account'>;
export type AccountUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Account'>;
export type AccountCheckedCreateInput = $CheckedCreateInput<$Schema, 'Account'>;
export type AccountUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Account'>;
export type AccountCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Account'>;
export type AccountGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Account', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Account', Args, Options>;
export type VerificationFindManyArgs = $FindManyArgs<$Schema, 'Verification'>;
export type VerificationFindUniqueArgs = $FindUniqueArgs<$Schema, 'Verification'>;
export type VerificationFindFirstArgs = $FindFirstArgs<$Schema, 'Verification'>;
export type VerificationExistsArgs = $ExistsArgs<$Schema, 'Verification'>;
export type VerificationCreateArgs = $CreateArgs<$Schema, 'Verification'>;
export type VerificationCreateManyArgs = $CreateManyArgs<$Schema, 'Verification'>;
export type VerificationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Verification'>;
export type VerificationUpdateArgs = $UpdateArgs<$Schema, 'Verification'>;
export type VerificationUpdateManyArgs = $UpdateManyArgs<$Schema, 'Verification'>;
export type VerificationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Verification'>;
export type VerificationUpsertArgs = $UpsertArgs<$Schema, 'Verification'>;
export type VerificationDeleteArgs = $DeleteArgs<$Schema, 'Verification'>;
export type VerificationDeleteManyArgs = $DeleteManyArgs<$Schema, 'Verification'>;
export type VerificationCountArgs = $CountArgs<$Schema, 'Verification'>;
export type VerificationAggregateArgs = $AggregateArgs<$Schema, 'Verification'>;
export type VerificationGroupByArgs = $GroupByArgs<$Schema, 'Verification'>;
export type VerificationWhereInput = $WhereInput<$Schema, 'Verification'>;
export type VerificationSelect = $SelectInput<$Schema, 'Verification'>;
export type VerificationInclude = $IncludeInput<$Schema, 'Verification'>;
export type VerificationOmit = $OmitInput<$Schema, 'Verification'>;
export type VerificationUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Verification'>;
export type VerificationCheckedCreateInput = $CheckedCreateInput<$Schema, 'Verification'>;
export type VerificationUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Verification'>;
export type VerificationCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Verification'>;
export type VerificationGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Verification', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Verification', Args, Options>;
export type DogFindManyArgs = $FindManyArgs<$Schema, 'Dog'>;
export type DogFindUniqueArgs = $FindUniqueArgs<$Schema, 'Dog'>;
export type DogFindFirstArgs = $FindFirstArgs<$Schema, 'Dog'>;
export type DogExistsArgs = $ExistsArgs<$Schema, 'Dog'>;
export type DogCreateArgs = $CreateArgs<$Schema, 'Dog'>;
export type DogCreateManyArgs = $CreateManyArgs<$Schema, 'Dog'>;
export type DogCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Dog'>;
export type DogUpdateArgs = $UpdateArgs<$Schema, 'Dog'>;
export type DogUpdateManyArgs = $UpdateManyArgs<$Schema, 'Dog'>;
export type DogUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Dog'>;
export type DogUpsertArgs = $UpsertArgs<$Schema, 'Dog'>;
export type DogDeleteArgs = $DeleteArgs<$Schema, 'Dog'>;
export type DogDeleteManyArgs = $DeleteManyArgs<$Schema, 'Dog'>;
export type DogCountArgs = $CountArgs<$Schema, 'Dog'>;
export type DogAggregateArgs = $AggregateArgs<$Schema, 'Dog'>;
export type DogGroupByArgs = $GroupByArgs<$Schema, 'Dog'>;
export type DogWhereInput = $WhereInput<$Schema, 'Dog'>;
export type DogSelect = $SelectInput<$Schema, 'Dog'>;
export type DogInclude = $IncludeInput<$Schema, 'Dog'>;
export type DogOmit = $OmitInput<$Schema, 'Dog'>;
export type DogUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Dog'>;
export type DogCheckedCreateInput = $CheckedCreateInput<$Schema, 'Dog'>;
export type DogUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Dog'>;
export type DogCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Dog'>;
export type DogGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Dog', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Dog', Args, Options>;
export type CategoryFindManyArgs = $FindManyArgs<$Schema, 'Category'>;
export type CategoryFindUniqueArgs = $FindUniqueArgs<$Schema, 'Category'>;
export type CategoryFindFirstArgs = $FindFirstArgs<$Schema, 'Category'>;
export type CategoryExistsArgs = $ExistsArgs<$Schema, 'Category'>;
export type CategoryCreateArgs = $CreateArgs<$Schema, 'Category'>;
export type CategoryCreateManyArgs = $CreateManyArgs<$Schema, 'Category'>;
export type CategoryCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Category'>;
export type CategoryUpdateArgs = $UpdateArgs<$Schema, 'Category'>;
export type CategoryUpdateManyArgs = $UpdateManyArgs<$Schema, 'Category'>;
export type CategoryUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Category'>;
export type CategoryUpsertArgs = $UpsertArgs<$Schema, 'Category'>;
export type CategoryDeleteArgs = $DeleteArgs<$Schema, 'Category'>;
export type CategoryDeleteManyArgs = $DeleteManyArgs<$Schema, 'Category'>;
export type CategoryCountArgs = $CountArgs<$Schema, 'Category'>;
export type CategoryAggregateArgs = $AggregateArgs<$Schema, 'Category'>;
export type CategoryGroupByArgs = $GroupByArgs<$Schema, 'Category'>;
export type CategoryWhereInput = $WhereInput<$Schema, 'Category'>;
export type CategorySelect = $SelectInput<$Schema, 'Category'>;
export type CategoryInclude = $IncludeInput<$Schema, 'Category'>;
export type CategoryOmit = $OmitInput<$Schema, 'Category'>;
export type CategoryUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Category'>;
export type CategoryCheckedCreateInput = $CheckedCreateInput<$Schema, 'Category'>;
export type CategoryUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Category'>;
export type CategoryCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Category'>;
export type CategoryGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Category', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Category', Args, Options>;
export type AmenityFindManyArgs = $FindManyArgs<$Schema, 'Amenity'>;
export type AmenityFindUniqueArgs = $FindUniqueArgs<$Schema, 'Amenity'>;
export type AmenityFindFirstArgs = $FindFirstArgs<$Schema, 'Amenity'>;
export type AmenityExistsArgs = $ExistsArgs<$Schema, 'Amenity'>;
export type AmenityCreateArgs = $CreateArgs<$Schema, 'Amenity'>;
export type AmenityCreateManyArgs = $CreateManyArgs<$Schema, 'Amenity'>;
export type AmenityCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Amenity'>;
export type AmenityUpdateArgs = $UpdateArgs<$Schema, 'Amenity'>;
export type AmenityUpdateManyArgs = $UpdateManyArgs<$Schema, 'Amenity'>;
export type AmenityUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Amenity'>;
export type AmenityUpsertArgs = $UpsertArgs<$Schema, 'Amenity'>;
export type AmenityDeleteArgs = $DeleteArgs<$Schema, 'Amenity'>;
export type AmenityDeleteManyArgs = $DeleteManyArgs<$Schema, 'Amenity'>;
export type AmenityCountArgs = $CountArgs<$Schema, 'Amenity'>;
export type AmenityAggregateArgs = $AggregateArgs<$Schema, 'Amenity'>;
export type AmenityGroupByArgs = $GroupByArgs<$Schema, 'Amenity'>;
export type AmenityWhereInput = $WhereInput<$Schema, 'Amenity'>;
export type AmenitySelect = $SelectInput<$Schema, 'Amenity'>;
export type AmenityInclude = $IncludeInput<$Schema, 'Amenity'>;
export type AmenityOmit = $OmitInput<$Schema, 'Amenity'>;
export type AmenityUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Amenity'>;
export type AmenityCheckedCreateInput = $CheckedCreateInput<$Schema, 'Amenity'>;
export type AmenityUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Amenity'>;
export type AmenityCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Amenity'>;
export type AmenityGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Amenity', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Amenity', Args, Options>;
export type AmenityOnCategoryFindManyArgs = $FindManyArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryFindUniqueArgs = $FindUniqueArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryFindFirstArgs = $FindFirstArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryExistsArgs = $ExistsArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryCreateArgs = $CreateArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryCreateManyArgs = $CreateManyArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
  $Schema,
  'AmenityOnCategory'
>;
export type AmenityOnCategoryUpdateArgs = $UpdateArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryUpdateManyArgs = $UpdateManyArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
  $Schema,
  'AmenityOnCategory'
>;
export type AmenityOnCategoryUpsertArgs = $UpsertArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryDeleteArgs = $DeleteArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryDeleteManyArgs = $DeleteManyArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryCountArgs = $CountArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryAggregateArgs = $AggregateArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryGroupByArgs = $GroupByArgs<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryWhereInput = $WhereInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategorySelect = $SelectInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryInclude = $IncludeInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryOmit = $OmitInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryUncheckedCreateInput = $UncheckedCreateInput<
  $Schema,
  'AmenityOnCategory'
>;
export type AmenityOnCategoryCheckedCreateInput = $CheckedCreateInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryUncheckedUpdateInput = $UncheckedUpdateInput<
  $Schema,
  'AmenityOnCategory'
>;
export type AmenityOnCategoryCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'AmenityOnCategory'>;
export type AmenityOnCategoryGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'AmenityOnCategory', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'AmenityOnCategory', Args, Options>;
export type SpotFindManyArgs = $FindManyArgs<$Schema, 'Spot'>;
export type SpotFindUniqueArgs = $FindUniqueArgs<$Schema, 'Spot'>;
export type SpotFindFirstArgs = $FindFirstArgs<$Schema, 'Spot'>;
export type SpotExistsArgs = $ExistsArgs<$Schema, 'Spot'>;
export type SpotCreateArgs = $CreateArgs<$Schema, 'Spot'>;
export type SpotCreateManyArgs = $CreateManyArgs<$Schema, 'Spot'>;
export type SpotCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Spot'>;
export type SpotUpdateArgs = $UpdateArgs<$Schema, 'Spot'>;
export type SpotUpdateManyArgs = $UpdateManyArgs<$Schema, 'Spot'>;
export type SpotUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Spot'>;
export type SpotUpsertArgs = $UpsertArgs<$Schema, 'Spot'>;
export type SpotDeleteArgs = $DeleteArgs<$Schema, 'Spot'>;
export type SpotDeleteManyArgs = $DeleteManyArgs<$Schema, 'Spot'>;
export type SpotCountArgs = $CountArgs<$Schema, 'Spot'>;
export type SpotAggregateArgs = $AggregateArgs<$Schema, 'Spot'>;
export type SpotGroupByArgs = $GroupByArgs<$Schema, 'Spot'>;
export type SpotWhereInput = $WhereInput<$Schema, 'Spot'>;
export type SpotSelect = $SelectInput<$Schema, 'Spot'>;
export type SpotInclude = $IncludeInput<$Schema, 'Spot'>;
export type SpotOmit = $OmitInput<$Schema, 'Spot'>;
export type SpotUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Spot'>;
export type SpotCheckedCreateInput = $CheckedCreateInput<$Schema, 'Spot'>;
export type SpotUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Spot'>;
export type SpotCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Spot'>;
export type SpotGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Spot', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Spot', Args, Options>;
export type SpotAmenityFindManyArgs = $FindManyArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityFindUniqueArgs = $FindUniqueArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityFindFirstArgs = $FindFirstArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityExistsArgs = $ExistsArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityCreateArgs = $CreateArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityCreateManyArgs = $CreateManyArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityUpdateArgs = $UpdateArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityUpdateManyArgs = $UpdateManyArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityUpsertArgs = $UpsertArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityDeleteArgs = $DeleteArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityDeleteManyArgs = $DeleteManyArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityCountArgs = $CountArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityAggregateArgs = $AggregateArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityGroupByArgs = $GroupByArgs<$Schema, 'SpotAmenity'>;
export type SpotAmenityWhereInput = $WhereInput<$Schema, 'SpotAmenity'>;
export type SpotAmenitySelect = $SelectInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityInclude = $IncludeInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityOmit = $OmitInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityCheckedCreateInput = $CheckedCreateInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'SpotAmenity'>;
export type SpotAmenityGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'SpotAmenity', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SpotAmenity', Args, Options>;
export type SpotPhotoFindManyArgs = $FindManyArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoFindUniqueArgs = $FindUniqueArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoFindFirstArgs = $FindFirstArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoExistsArgs = $ExistsArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoCreateArgs = $CreateArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoCreateManyArgs = $CreateManyArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoUpdateArgs = $UpdateArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoUpdateManyArgs = $UpdateManyArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoUpsertArgs = $UpsertArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoDeleteArgs = $DeleteArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoDeleteManyArgs = $DeleteManyArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoCountArgs = $CountArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoAggregateArgs = $AggregateArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoGroupByArgs = $GroupByArgs<$Schema, 'SpotPhoto'>;
export type SpotPhotoWhereInput = $WhereInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoSelect = $SelectInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoInclude = $IncludeInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoOmit = $OmitInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoCheckedCreateInput = $CheckedCreateInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'SpotPhoto'>;
export type SpotPhotoGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'SpotPhoto', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'SpotPhoto', Args, Options>;
export type VoteFindManyArgs = $FindManyArgs<$Schema, 'Vote'>;
export type VoteFindUniqueArgs = $FindUniqueArgs<$Schema, 'Vote'>;
export type VoteFindFirstArgs = $FindFirstArgs<$Schema, 'Vote'>;
export type VoteExistsArgs = $ExistsArgs<$Schema, 'Vote'>;
export type VoteCreateArgs = $CreateArgs<$Schema, 'Vote'>;
export type VoteCreateManyArgs = $CreateManyArgs<$Schema, 'Vote'>;
export type VoteCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Vote'>;
export type VoteUpdateArgs = $UpdateArgs<$Schema, 'Vote'>;
export type VoteUpdateManyArgs = $UpdateManyArgs<$Schema, 'Vote'>;
export type VoteUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Vote'>;
export type VoteUpsertArgs = $UpsertArgs<$Schema, 'Vote'>;
export type VoteDeleteArgs = $DeleteArgs<$Schema, 'Vote'>;
export type VoteDeleteManyArgs = $DeleteManyArgs<$Schema, 'Vote'>;
export type VoteCountArgs = $CountArgs<$Schema, 'Vote'>;
export type VoteAggregateArgs = $AggregateArgs<$Schema, 'Vote'>;
export type VoteGroupByArgs = $GroupByArgs<$Schema, 'Vote'>;
export type VoteWhereInput = $WhereInput<$Schema, 'Vote'>;
export type VoteSelect = $SelectInput<$Schema, 'Vote'>;
export type VoteInclude = $IncludeInput<$Schema, 'Vote'>;
export type VoteOmit = $OmitInput<$Schema, 'Vote'>;
export type VoteUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Vote'>;
export type VoteCheckedCreateInput = $CheckedCreateInput<$Schema, 'Vote'>;
export type VoteUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Vote'>;
export type VoteCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Vote'>;
export type VoteGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Vote', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Vote', Args, Options>;
export type ReviewFindManyArgs = $FindManyArgs<$Schema, 'Review'>;
export type ReviewFindUniqueArgs = $FindUniqueArgs<$Schema, 'Review'>;
export type ReviewFindFirstArgs = $FindFirstArgs<$Schema, 'Review'>;
export type ReviewExistsArgs = $ExistsArgs<$Schema, 'Review'>;
export type ReviewCreateArgs = $CreateArgs<$Schema, 'Review'>;
export type ReviewCreateManyArgs = $CreateManyArgs<$Schema, 'Review'>;
export type ReviewCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Review'>;
export type ReviewUpdateArgs = $UpdateArgs<$Schema, 'Review'>;
export type ReviewUpdateManyArgs = $UpdateManyArgs<$Schema, 'Review'>;
export type ReviewUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Review'>;
export type ReviewUpsertArgs = $UpsertArgs<$Schema, 'Review'>;
export type ReviewDeleteArgs = $DeleteArgs<$Schema, 'Review'>;
export type ReviewDeleteManyArgs = $DeleteManyArgs<$Schema, 'Review'>;
export type ReviewCountArgs = $CountArgs<$Schema, 'Review'>;
export type ReviewAggregateArgs = $AggregateArgs<$Schema, 'Review'>;
export type ReviewGroupByArgs = $GroupByArgs<$Schema, 'Review'>;
export type ReviewWhereInput = $WhereInput<$Schema, 'Review'>;
export type ReviewSelect = $SelectInput<$Schema, 'Review'>;
export type ReviewInclude = $IncludeInput<$Schema, 'Review'>;
export type ReviewOmit = $OmitInput<$Schema, 'Review'>;
export type ReviewUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Review'>;
export type ReviewCheckedCreateInput = $CheckedCreateInput<$Schema, 'Review'>;
export type ReviewUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Review'>;
export type ReviewCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Review'>;
export type ReviewGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Review', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Review', Args, Options>;
export type ReportFindManyArgs = $FindManyArgs<$Schema, 'Report'>;
export type ReportFindUniqueArgs = $FindUniqueArgs<$Schema, 'Report'>;
export type ReportFindFirstArgs = $FindFirstArgs<$Schema, 'Report'>;
export type ReportExistsArgs = $ExistsArgs<$Schema, 'Report'>;
export type ReportCreateArgs = $CreateArgs<$Schema, 'Report'>;
export type ReportCreateManyArgs = $CreateManyArgs<$Schema, 'Report'>;
export type ReportCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'Report'>;
export type ReportUpdateArgs = $UpdateArgs<$Schema, 'Report'>;
export type ReportUpdateManyArgs = $UpdateManyArgs<$Schema, 'Report'>;
export type ReportUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'Report'>;
export type ReportUpsertArgs = $UpsertArgs<$Schema, 'Report'>;
export type ReportDeleteArgs = $DeleteArgs<$Schema, 'Report'>;
export type ReportDeleteManyArgs = $DeleteManyArgs<$Schema, 'Report'>;
export type ReportCountArgs = $CountArgs<$Schema, 'Report'>;
export type ReportAggregateArgs = $AggregateArgs<$Schema, 'Report'>;
export type ReportGroupByArgs = $GroupByArgs<$Schema, 'Report'>;
export type ReportWhereInput = $WhereInput<$Schema, 'Report'>;
export type ReportSelect = $SelectInput<$Schema, 'Report'>;
export type ReportInclude = $IncludeInput<$Schema, 'Report'>;
export type ReportOmit = $OmitInput<$Schema, 'Report'>;
export type ReportUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'Report'>;
export type ReportCheckedCreateInput = $CheckedCreateInput<$Schema, 'Report'>;
export type ReportUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'Report'>;
export type ReportCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'Report'>;
export type ReportGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'Report', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'Report', Args, Options>;
export type AdminActionFindManyArgs = $FindManyArgs<$Schema, 'AdminAction'>;
export type AdminActionFindUniqueArgs = $FindUniqueArgs<$Schema, 'AdminAction'>;
export type AdminActionFindFirstArgs = $FindFirstArgs<$Schema, 'AdminAction'>;
export type AdminActionExistsArgs = $ExistsArgs<$Schema, 'AdminAction'>;
export type AdminActionCreateArgs = $CreateArgs<$Schema, 'AdminAction'>;
export type AdminActionCreateManyArgs = $CreateManyArgs<$Schema, 'AdminAction'>;
export type AdminActionCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'AdminAction'>;
export type AdminActionUpdateArgs = $UpdateArgs<$Schema, 'AdminAction'>;
export type AdminActionUpdateManyArgs = $UpdateManyArgs<$Schema, 'AdminAction'>;
export type AdminActionUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'AdminAction'>;
export type AdminActionUpsertArgs = $UpsertArgs<$Schema, 'AdminAction'>;
export type AdminActionDeleteArgs = $DeleteArgs<$Schema, 'AdminAction'>;
export type AdminActionDeleteManyArgs = $DeleteManyArgs<$Schema, 'AdminAction'>;
export type AdminActionCountArgs = $CountArgs<$Schema, 'AdminAction'>;
export type AdminActionAggregateArgs = $AggregateArgs<$Schema, 'AdminAction'>;
export type AdminActionGroupByArgs = $GroupByArgs<$Schema, 'AdminAction'>;
export type AdminActionWhereInput = $WhereInput<$Schema, 'AdminAction'>;
export type AdminActionSelect = $SelectInput<$Schema, 'AdminAction'>;
export type AdminActionInclude = $IncludeInput<$Schema, 'AdminAction'>;
export type AdminActionOmit = $OmitInput<$Schema, 'AdminAction'>;
export type AdminActionUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'AdminAction'>;
export type AdminActionCheckedCreateInput = $CheckedCreateInput<$Schema, 'AdminAction'>;
export type AdminActionUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'AdminAction'>;
export type AdminActionCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'AdminAction'>;
export type AdminActionGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'AdminAction', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'AdminAction', Args, Options>;
export type FeatureRequestFindManyArgs = $FindManyArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestFindUniqueArgs = $FindUniqueArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestFindFirstArgs = $FindFirstArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestExistsArgs = $ExistsArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestCreateArgs = $CreateArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestCreateManyArgs = $CreateManyArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
  $Schema,
  'FeatureRequest'
>;
export type FeatureRequestUpdateArgs = $UpdateArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestUpdateManyArgs = $UpdateManyArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
  $Schema,
  'FeatureRequest'
>;
export type FeatureRequestUpsertArgs = $UpsertArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestDeleteArgs = $DeleteArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestDeleteManyArgs = $DeleteManyArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestCountArgs = $CountArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestAggregateArgs = $AggregateArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestGroupByArgs = $GroupByArgs<$Schema, 'FeatureRequest'>;
export type FeatureRequestWhereInput = $WhereInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestSelect = $SelectInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestInclude = $IncludeInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestOmit = $OmitInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestCheckedCreateInput = $CheckedCreateInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'FeatureRequest'>;
export type FeatureRequestGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'FeatureRequest', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'FeatureRequest', Args, Options>;
export type FeatureVoteFindManyArgs = $FindManyArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteFindUniqueArgs = $FindUniqueArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteFindFirstArgs = $FindFirstArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteExistsArgs = $ExistsArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteCreateArgs = $CreateArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteCreateManyArgs = $CreateManyArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteUpdateArgs = $UpdateArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteUpdateManyArgs = $UpdateManyArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteUpsertArgs = $UpsertArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteDeleteArgs = $DeleteArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteDeleteManyArgs = $DeleteManyArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteCountArgs = $CountArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteAggregateArgs = $AggregateArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteGroupByArgs = $GroupByArgs<$Schema, 'FeatureVote'>;
export type FeatureVoteWhereInput = $WhereInput<$Schema, 'FeatureVote'>;
export type FeatureVoteSelect = $SelectInput<$Schema, 'FeatureVote'>;
export type FeatureVoteInclude = $IncludeInput<$Schema, 'FeatureVote'>;
export type FeatureVoteOmit = $OmitInput<$Schema, 'FeatureVote'>;
export type FeatureVoteUncheckedCreateInput = $UncheckedCreateInput<$Schema, 'FeatureVote'>;
export type FeatureVoteCheckedCreateInput = $CheckedCreateInput<$Schema, 'FeatureVote'>;
export type FeatureVoteUncheckedUpdateInput = $UncheckedUpdateInput<$Schema, 'FeatureVote'>;
export type FeatureVoteCheckedUpdateInput = $CheckedUpdateInput<$Schema, 'FeatureVote'>;
export type FeatureVoteGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'FeatureVote', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'FeatureVote', Args, Options>;
export type ModeratorApplicationFindManyArgs = $FindManyArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationFindUniqueArgs = $FindUniqueArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationFindFirstArgs = $FindFirstArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationExistsArgs = $ExistsArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationCreateArgs = $CreateArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationCreateManyArgs = $CreateManyArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationCreateManyAndReturnArgs = $CreateManyAndReturnArgs<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationUpdateArgs = $UpdateArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationUpdateManyArgs = $UpdateManyArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationUpsertArgs = $UpsertArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationDeleteArgs = $DeleteArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationDeleteManyArgs = $DeleteManyArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationCountArgs = $CountArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationAggregateArgs = $AggregateArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationGroupByArgs = $GroupByArgs<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationWhereInput = $WhereInput<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationSelect = $SelectInput<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationInclude = $IncludeInput<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationOmit = $OmitInput<$Schema, 'ModeratorApplication'>;
export type ModeratorApplicationUncheckedCreateInput = $UncheckedCreateInput<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationCheckedCreateInput = $CheckedCreateInput<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationUncheckedUpdateInput = $UncheckedUpdateInput<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationCheckedUpdateInput = $CheckedUpdateInput<
  $Schema,
  'ModeratorApplication'
>;
export type ModeratorApplicationGetPayload<
  Args extends $SelectIncludeOmit<$Schema, 'ModeratorApplication', true>,
  Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>,
> = $Result<$Schema, 'ModeratorApplication', Args, Options>;
