//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from './schema';
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from '@zenstackhq/orm';
export type User = $ModelResult<$Schema, 'User'>;
export type Session = $ModelResult<$Schema, 'Session'>;
export type Account = $ModelResult<$Schema, 'Account'>;
export type Verification = $ModelResult<$Schema, 'Verification'>;
export type Dog = $ModelResult<$Schema, 'Dog'>;
export type Category = $ModelResult<$Schema, 'Category'>;
export type Amenity = $ModelResult<$Schema, 'Amenity'>;
export type AmenityOnCategory = $ModelResult<$Schema, 'AmenityOnCategory'>;
export type Spot = $ModelResult<$Schema, 'Spot'>;
export type SpotAmenity = $ModelResult<$Schema, 'SpotAmenity'>;
export type SpotPhoto = $ModelResult<$Schema, 'SpotPhoto'>;
export type Vote = $ModelResult<$Schema, 'Vote'>;
export type Review = $ModelResult<$Schema, 'Review'>;
export type Report = $ModelResult<$Schema, 'Report'>;
export type AdminAction = $ModelResult<$Schema, 'AdminAction'>;
export type FeatureRequest = $ModelResult<$Schema, 'FeatureRequest'>;
export type FeatureVote = $ModelResult<$Schema, 'FeatureVote'>;
export type Auth = $TypeDefResult<$Schema, 'Auth'>;
export const UserRole = $schema.enums.UserRole.values;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
export const SpotType = $schema.enums.SpotType.values;
export type SpotType = (typeof SpotType)[keyof typeof SpotType];
export const SpotStatus = $schema.enums.SpotStatus.values;
export type SpotStatus = (typeof SpotStatus)[keyof typeof SpotStatus];
export const TaxonomyStatus = $schema.enums.TaxonomyStatus.values;
export type TaxonomyStatus = (typeof TaxonomyStatus)[keyof typeof TaxonomyStatus];
export const VoteValue = $schema.enums.VoteValue.values;
export type VoteValue = (typeof VoteValue)[keyof typeof VoteValue];
export const PhotoStatus = $schema.enums.PhotoStatus.values;
export type PhotoStatus = (typeof PhotoStatus)[keyof typeof PhotoStatus];
export const ReviewStatus = $schema.enums.ReviewStatus.values;
export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus];
export const ReportTarget = $schema.enums.ReportTarget.values;
export type ReportTarget = (typeof ReportTarget)[keyof typeof ReportTarget];
export const ReportReason = $schema.enums.ReportReason.values;
export type ReportReason = (typeof ReportReason)[keyof typeof ReportReason];
export const FeatureStatus = $schema.enums.FeatureStatus.values;
export type FeatureStatus = (typeof FeatureStatus)[keyof typeof FeatureStatus];
export const AdminActionType = $schema.enums.AdminActionType.values;
export type AdminActionType = (typeof AdminActionType)[keyof typeof AdminActionType];
