/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Acknowledgement that the account was deleted.
 *
 * @param ok The account was deleted (or already gone).
 */
@Serializable

data class AccountDeletionResponse (

    /* The account was deleted (or already gone). */
    @SerialName(value = "ok")
    val ok: AccountDeletionResponse.Ok

) {

    /**
     * The account was deleted (or already gone).
     *
     * Values: TRUE
     */
    @Serializable
    enum class Ok(val value: kotlin.Boolean) {
        @SerialName(value = "true") TRUE(true);
    }

}

