/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A spot amenity / facility tag.
 *
 * @param id RFC 4122 UUID (v4).
 * @param slug 
 * @param label 
 * @param icon Icon name (Tabler / SF Symbol / Material).
 * @param sortOrder 
 * @param categoryIds Categories this amenity applies to (from `AmenityOnCategory`). Empty = applicable everywhere.
 */
@Serializable

data class Amenity (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    /* Icon name (Tabler / SF Symbol / Material). */
    @SerialName(value = "icon")
    val icon: kotlin.String?,

    @SerialName(value = "sortOrder")
    val sortOrder: kotlin.Int,

    /* Categories this amenity applies to (from `AmenityOnCategory`). Empty = applicable everywhere. */
    @SerialName(value = "categoryIds")
    val categoryIds: kotlin.collections.List<@Contextual java.util.UUID>

) {


}

