/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Uniform error envelope used by every API endpoint.
 *
 * @param error Machine-readable error code in UPPER_SNAKE_CASE.
 * @param message Human-readable explanation. Safe to display to end users.
 * @param details 
 */
@Serializable

data class ApiError (

    /* Machine-readable error code in UPPER_SNAKE_CASE. */
    @SerialName(value = "error")
    val error: kotlin.String,

    /* Human-readable explanation. Safe to display to end users. */
    @SerialName(value = "message")
    val message: kotlin.String,

    @Contextual @SerialName(value = "details")
    val details: kotlin.Any? = null

) {


}

