/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.AppConfigUpdateUrl

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Runtime configuration read by the mobile app on boot.
 *
 * @param minSupportedVersion Lowest app version still allowed to run. Below this, force an update.
 * @param latestVersion Latest released app version.
 * @param updateUrl 
 */
@Serializable

data class AppConfig (

    /* Lowest app version still allowed to run. Below this, force an update. */
    @SerialName(value = "minSupportedVersion")
    val minSupportedVersion: kotlin.String,

    /* Latest released app version. */
    @SerialName(value = "latestVersion")
    val latestVersion: kotlin.String,

    @SerialName(value = "updateUrl")
    val updateUrl: AppConfigUpdateUrl

) {


}

