/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Per-platform store URLs for the update prompt.
 *
 * @param ios App Store URL.
 * @param android Play Store URL.
 */
@Serializable

data class AppConfigUpdateUrl (

    /* App Store URL. */
    @Contextual @SerialName(value = "ios")
    val ios: java.net.URI,

    /* Play Store URL. */
    @Contextual @SerialName(value = "android")
    val android: java.net.URI

) {


}

