/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A bearer session token + optional expiry.
 *
 * @param token BetterAuth signed session token. Sent as `Authorization: Bearer <token>`.
 * @param expiresAt When the token expires, or null when the API does not surface it.
 */
@Serializable

data class AuthToken (

    /* BetterAuth signed session token. Sent as `Authorization: Bearer <token>`. */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* When the token expires, or null when the API does not surface it. */
    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.time.OffsetDateTime?

) {


}

