/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.SpotType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A spot category.
 *
 * @param id RFC 4122 UUID (v4).
 * @param slug 
 * @param label 
 * @param type 
 * @param icon Icon name (Tabler on web, mapped to SF Symbol / Material on mobile).
 * @param color Pin colour (hex).
 * @param sortOrder 
 */
@Serializable

data class Category (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: SpotType,

    /* Icon name (Tabler on web, mapped to SF Symbol / Material on mobile). */
    @SerialName(value = "icon")
    val icon: kotlin.String?,

    /* Pin colour (hex). */
    @SerialName(value = "color")
    val color: kotlin.String?,

    @SerialName(value = "sortOrder")
    val sortOrder: kotlin.Int

) {


}

