/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/v1/me/feature-requests`.
 *
 * @param title 
 * @param body 
 * @param component Area of the app: Kaart / Inzenden / Profiel / Anders.
 */
@Serializable

data class CreateFeatureRequest (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    /* Area of the app: Kaart / Inzenden / Profiel / Anders. */
    @SerialName(value = "component")
    val component: kotlin.String? = null

) {


}

