/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A dog profile.
 *
 * @param id RFC 4122 UUID (v4).
 * @param name 
 * @param breed 
 * @param birthYear 
 * @param birthDate ISO date of birth (YYYY-MM-DD).
 * @param photoUrl 
 * @param note 
 * @param createdAt RFC 3339 datetime in UTC.
 * @param updatedAt RFC 3339 datetime in UTC.
 */
@Serializable

data class Dog (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "breed")
    val breed: kotlin.String?,

    @SerialName(value = "birthYear")
    val birthYear: kotlin.Int?,

    /* ISO date of birth (YYYY-MM-DD). */
    @SerialName(value = "birthDate")
    val birthDate: kotlin.String?,

    @Contextual @SerialName(value = "photoUrl")
    val photoUrl: java.net.URI?,

    @SerialName(value = "note")
    val note: kotlin.String?,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

