/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Product-roadmap state of a community feature request.
 *
 * Values: CONSIDERING,PLANNED,DONE,DECLINED
 */
@Serializable
enum class FeatureStatus(val value: kotlin.String) {

    @SerialName(value = "CONSIDERING")
    CONSIDERING("CONSIDERING"),

    @SerialName(value = "PLANNED")
    PLANNED("PLANNED"),

    @SerialName(value = "DONE")
    DONE("DONE"),

    @SerialName(value = "DECLINED")
    DECLINED("DECLINED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FeatureStatus) "$data" else null

        /**
         * Returns a valid [FeatureStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FeatureStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


