/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Result of toggling an upvote on a feature request.
 *
 * @param requestId RFC 4122 UUID (v4).
 * @param upvoteCount 
 * @param viewerHasVoted 
 */
@Serializable

data class FeatureVoteResponse (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "requestId")
    val requestId: java.util.UUID,

    @SerialName(value = "upvoteCount")
    val upvoteCount: kotlin.Int,

    @SerialName(value = "viewerHasVoted")
    val viewerHasVoted: kotlin.Boolean

) {


}

