/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.FeatureRequestAuthor
import nl.devrijehond.app.api.models.FeatureStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A community feature request.
 *
 * @param id RFC 4122 UUID (v4).
 * @param title 
 * @param body 
 * @param component Area of the app this concerns.
 * @param status 
 * @param upvoteCount 
 * @param viewerHasVoted Whether the signed-in user has upvoted. False for anonymous reads.
 * @param author 
 * @param createdAt RFC 3339 datetime in UTC.
 */
@Serializable

data class FeatureRequest (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "body")
    val body: kotlin.String?,

    /* Area of the app this concerns. */
    @SerialName(value = "component")
    val component: kotlin.String?,

    @Contextual @SerialName(value = "status")
    val status: FeatureStatus,

    @SerialName(value = "upvoteCount")
    val upvoteCount: kotlin.Int,

    /* Whether the signed-in user has upvoted. False for anonymous reads. */
    @SerialName(value = "viewerHasVoted")
    val viewerHasVoted: kotlin.Boolean,

    @SerialName(value = "author")
    val author: FeatureRequestAuthor,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

