/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/auth/sign-in/magic-link`.
 *
 * @param email Email to send the magic link to.
 * @param callbackURL Deep link the interstitial hops to after verifying.
 */
@Serializable

data class MagicLinkRequest (

    /* Email to send the magic link to. */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* Deep link the interstitial hops to after verifying. */
    @SerialName(value = "callbackURL")
    val callbackURL: kotlin.String? = null

) {


}

