/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A clustered group of nearby spots on the map.
 *
 * @param lat Latitude in decimal degrees (WGS84 / EPSG:4326).
 * @param lng Longitude in decimal degrees (WGS84 / EPSG:4326).
 * @param count Number of spots in this cluster.
 */
@Serializable

data class MapCluster (

    /* Latitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lat")
    val lat: java.math.BigDecimal,

    /* Longitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lng")
    val lng: java.math.BigDecimal,

    /* Number of spots in this cluster. */
    @SerialName(value = "count")
    val count: kotlin.Int

) {


}

