/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `PATCH /api/v1/me`.
 *
 * @param name 
 * @param handle Unique @username (lowercase, 3–30 chars).
 * @param bio 
 * @param image Avatar URL (uploaded to S3 first).
 */
@Serializable

data class MeProfilePatch (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Unique @username (lowercase, 3–30 chars). */
    @SerialName(value = "handle")
    val handle: kotlin.String? = null,

    @SerialName(value = "bio")
    val bio: kotlin.String? = null,

    /* Avatar URL (uploaded to S3 first). */
    @Contextual @SerialName(value = "image")
    val image: java.net.URI? = null

) {


}

