/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.Dog
import nl.devrijehond.app.api.models.UserRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Authenticated user profile (`GET /api/v1/me`).
 *
 * @param id RFC 4122 UUID (v4).
 * @param email 
 * @param name 
 * @param handle @username.
 * @param bio 
 * @param image Avatar URL.
 * @param role 
 * @param reputation Contribution reputation score.
 * @param dogs 
 * @param createdAt RFC 3339 datetime in UTC.
 */
@Serializable

data class MeProfile (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String?,

    /* @username. */
    @SerialName(value = "handle")
    val handle: kotlin.String?,

    @SerialName(value = "bio")
    val bio: kotlin.String?,

    /* Avatar URL. */
    @Contextual @SerialName(value = "image")
    val image: java.net.URI?,

    @Contextual @SerialName(value = "role")
    val role: UserRole,

    /* Contribution reputation score. */
    @SerialName(value = "reputation")
    val reputation: kotlin.Int,

    @SerialName(value = "dogs")
    val dogs: kotlin.collections.List<Dog>,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

