/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Decision state of a moderator application.
 *
 * Values: PENDING,APPROVED,REJECTED
 */
@Serializable
enum class ModeratorApplicationStatus(val value: kotlin.String) {

    @SerialName(value = "PENDING")
    PENDING("PENDING"),

    @SerialName(value = "APPROVED")
    APPROVED("APPROVED"),

    @SerialName(value = "REJECTED")
    REJECTED("REJECTED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ModeratorApplicationStatus) "$data" else null

        /**
         * Returns a valid [ModeratorApplicationStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ModeratorApplicationStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


