/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.SpotStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `PATCH /api/v1/me/spots/:id/moderate` (staff only).
 *
 * @param status New spot status: VERIFIED | UNVERIFIED | HIDDEN | REMOVED.
 */
@Serializable

data class ModerateSpotRequest (

    /* New spot status: VERIFIED | UNVERIFIED | HIDDEN | REMOVED. */
    @Contextual @SerialName(value = "status")
    val status: SpotStatus

) {


}

