/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Why a piece of content was reported.
 *
 * Values: DUPLICATE,SPAM,WRONG_INFO,INAPPROPRIATE,OTHER
 */
@Serializable
enum class ReportReason(val value: kotlin.String) {

    @SerialName(value = "DUPLICATE")
    DUPLICATE("DUPLICATE"),

    @SerialName(value = "SPAM")
    SPAM("SPAM"),

    @SerialName(value = "WRONG_INFO")
    WRONG_INFO("WRONG_INFO"),

    @SerialName(value = "INAPPROPRIATE")
    INAPPROPRIATE("INAPPROPRIATE"),

    @SerialName(value = "OTHER")
    OTHER("OTHER");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ReportReason) "$data" else null

        /**
         * Returns a valid [ReportReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ReportReason? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


