/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.ReviewAuthor

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A spot review.
 *
 * @param id RFC 4122 UUID (v4).
 * @param spotId RFC 4122 UUID (v4).
 * @param stars Star rating, 0–5.
 * @param body 
 * @param helpfulCount 
 * @param author 
 * @param createdAt RFC 3339 datetime in UTC.
 */
@Serializable

data class Review (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "spotId")
    val spotId: java.util.UUID,

    /* Star rating, 0–5. */
    @SerialName(value = "stars")
    val stars: kotlin.Int,

    @SerialName(value = "body")
    val body: kotlin.String?,

    @SerialName(value = "helpfulCount")
    val helpfulCount: kotlin.Int,

    @SerialName(value = "author")
    val author: ReviewAuthor,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

