/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.SpotStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Community-verification status + denormalised vote score.
 *
 * @param status 
 * @param netScore Weighted confirm − deny score.
 * @param confirmCount 
 * @param denyCount 
 * @param verifiedAt When the spot reached VERIFIED, or null.
 */
@Serializable

data class SpotVerification (

    @Contextual @SerialName(value = "status")
    val status: SpotStatus,

    /* Weighted confirm − deny score. */
    @Contextual @SerialName(value = "netScore")
    val netScore: java.math.BigDecimal,

    @SerialName(value = "confirmCount")
    val confirmCount: kotlin.Int,

    @SerialName(value = "denyCount")
    val denyCount: kotlin.Int,

    /* When the spot reached VERIFIED, or null. */
    @Contextual @SerialName(value = "verifiedAt")
    val verifiedAt: java.time.OffsetDateTime?

) {


}

