/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.SpotSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Cursor-paginated list of spots.
 *
 * @param items 
 * @param nextCursor Cursor for the next page, or null when this is the last page.
 */
@Serializable

data class SpotsResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<SpotSummary>,

    /* Cursor for the next page, or null when this is the last page. */
    @SerialName(value = "nextCursor")
    val nextCursor: kotlin.String?

) {


}

