/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.SpotRating
import nl.devrijehond.app.api.models.SpotStatus
import nl.devrijehond.app.api.models.SpotType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Lightweight spot summary for map markers + list rows.
 *
 * @param id RFC 4122 UUID (v4).
 * @param slug URL-safe slug (lowercase, hyphenated).
 * @param type 
 * @param name 
 * @param categoryId RFC 4122 UUID (v4).
 * @param status 
 * @param lat Latitude in decimal degrees (WGS84 / EPSG:4326).
 * @param lng Longitude in decimal degrees (WGS84 / EPSG:4326).
 * @param rating 
 * @param photoUrl First photo URL for the list thumbnail, or null.
 * @param updatedAt RFC 3339 datetime in UTC.
 */
@Serializable

data class SpotSummary (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* URL-safe slug (lowercase, hyphenated). */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: SpotType,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "categoryId")
    val categoryId: java.util.UUID,

    @Contextual @SerialName(value = "status")
    val status: SpotStatus,

    /* Latitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lat")
    val lat: java.math.BigDecimal?,

    /* Longitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lng")
    val lng: java.math.BigDecimal?,

    @SerialName(value = "rating")
    val rating: SpotRating,

    /* First photo URL for the list thumbnail, or null. */
    @Contextual @SerialName(value = "photoUrl")
    val photoUrl: java.net.URI?,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

