/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Public reference to the user who submitted the spot.
 *
 * @param id RFC 4122 UUID (v4).
 * @param handle 
 * @param name 
 * @param image 
 */
@Serializable

data class SpotAuthor (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "handle")
    val handle: kotlin.String?,

    @SerialName(value = "name")
    val name: kotlin.String?,

    @Contextual @SerialName(value = "image")
    val image: java.net.URI?

) {


}

