/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One photo attached to a spot.
 *
 * @param id RFC 4122 UUID (v4).
 * @param url 
 * @param sortOrder 
 * @param createdAt RFC 3339 datetime in UTC.
 */
@Serializable

data class SpotPhoto (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "sortOrder")
    val sortOrder: kotlin.Int,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

