/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Moderation lifecycle. `UNVERIFIED` = live, awaiting community confirmation. `VERIFIED` = net weighted score reached threshold. `HIDDEN`/`REMOVED` = admin-only.
 *
 * Values: UNVERIFIED,VERIFIED,HIDDEN,REMOVED
 */
@Serializable
enum class SpotStatus(val value: kotlin.String) {

    @SerialName(value = "UNVERIFIED")
    UNVERIFIED("UNVERIFIED"),

    @SerialName(value = "VERIFIED")
    VERIFIED("VERIFIED"),

    @SerialName(value = "HIDDEN")
    HIDDEN("HIDDEN"),

    @SerialName(value = "REMOVED")
    REMOVED("REMOVED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SpotStatus) "$data" else null

        /**
         * Returns a valid [SpotStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SpotStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


