/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Denormalised review aggregate.
 *
 * @param average Mean star rating (0–5).
 * @param count Number of reviews.
 */
@Serializable

data class SpotRating (

    /* Mean star rating (0–5). */
    @Contextual @SerialName(value = "average")
    val average: java.math.BigDecimal,

    /* Number of reviews. */
    @SerialName(value = "count")
    val count: kotlin.Int

) {


}

