/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.ReportReason
import nl.devrijehond.app.api.models.ReportTarget

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/v1/me/reports`.
 *
 * @param targetType 
 * @param targetId Id of the spot / photo / review being reported.
 * @param reason 
 * @param note 
 */
@Serializable

data class SubmitReportRequest (

    @Contextual @SerialName(value = "targetType")
    val targetType: ReportTarget,

    /* Id of the spot / photo / review being reported. */
    @Contextual @SerialName(value = "targetId")
    val targetId: java.util.UUID,

    @Contextual @SerialName(value = "reason")
    val reason: ReportReason,

    @SerialName(value = "note")
    val note: kotlin.String? = null

) {


}

