/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.GeoPoint
import nl.devrijehond.app.api.models.SpotType
import nl.devrijehond.app.api.models.SubmitSpotRequestGeometry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/v1/me/spots`. A submitted spot goes live immediately as UNVERIFIED.
 *
 * @param type 
 * @param categoryId Category the spot belongs to.
 * @param name 
 * @param description 
 * @param geometry 
 * @param point Single lat/lng for a POI. Alternative to `geometry`.
 * @param polygon Polygon ring (≥ 3 lat/lng points) for a REGION. Alternative to `geometry`. The API closes the ring.
 * @param amenityIds Amenities offered at this spot.
 * @param photos Uploaded photo URLs (the client uploads to S3 first, then submits the resulting URLs).
 * @param address 
 * @param phone 
 * @param website 
 * @param hours 
 */
@Serializable

data class SubmitSpotRequest (

    @Contextual @SerialName(value = "type")
    val type: SpotType,

    /* Category the spot belongs to. */
    @Contextual @SerialName(value = "categoryId")
    val categoryId: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "geometry")
    val geometry: SubmitSpotRequestGeometry? = null,

    /* Single lat/lng for a POI. Alternative to `geometry`. */
    @SerialName(value = "point")
    val point: GeoPoint? = null,

    /* Polygon ring (≥ 3 lat/lng points) for a REGION. Alternative to `geometry`. The API closes the ring. */
    @SerialName(value = "polygon")
    val polygon: kotlin.collections.List<GeoPoint>? = null,

    /* Amenities offered at this spot. */
    @SerialName(value = "amenityIds")
    val amenityIds: kotlin.collections.List<@Contextual java.util.UUID>? = null,

    /* Uploaded photo URLs (the client uploads to S3 first, then submits the resulting URLs). */
    @SerialName(value = "photos")
    val photos: kotlin.collections.List<@Contextual java.net.URI>? = null,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    @Contextual @SerialName(value = "website")
    val website: java.net.URI? = null,

    @Contextual @SerialName(value = "hours")
    val hours: kotlin.Any? = null

) {


}

