/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * GeoJSON geometry. Provide this OR `point`/`polygon`.
 *
 * @param type 
 * @param coordinates 
 */
@Serializable

data class SubmitSpotRequestGeometry (

    @SerialName(value = "type")
    val type: SubmitSpotRequestGeometry.Type,

    @Contextual @SerialName(value = "coordinates")
    val coordinates: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: POINT,POLYGON
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Point") POINT("Point"),
        @SerialName(value = "Polygon") POLYGON("Polygon");
    }

}

