/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/v1/me/spots/:id/reviews`.
 *
 * @param stars Star rating, 0–5.
 * @param body 
 */
@Serializable

data class SubmitReviewRequest (

    /* Star rating, 0–5. */
    @SerialName(value = "stars")
    val stars: kotlin.Int,

    @SerialName(value = "body")
    val body: kotlin.String? = null

) {


}

