/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.GeoPoint
import nl.devrijehond.app.api.models.VoteValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `POST /api/v1/me/spots/:id/vote`.
 *
 * @param `value` 
 * @param proof Voter's current location, used for the proximity gate. When present and within range the vote is marked `proximityVerified` and weighted more heavily.
 */
@Serializable

data class SubmitVoteRequest (

    @Contextual @SerialName(value = "value")
    val `value`: VoteValue,

    /* Voter's current location, used for the proximity gate. When present and within range the vote is marked `proximityVerified` and weighted more heavily. */
    @SerialName(value = "proof")
    val proof: GeoPoint? = null

) {


}

