/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.Amenity
import nl.devrijehond.app.api.models.Category
import nl.devrijehond.app.api.models.SpotAuthor
import nl.devrijehond.app.api.models.SpotDetailGeometry
import nl.devrijehond.app.api.models.SpotPhoto
import nl.devrijehond.app.api.models.SpotRating
import nl.devrijehond.app.api.models.SpotStatus
import nl.devrijehond.app.api.models.SpotType
import nl.devrijehond.app.api.models.SpotVerification

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The created spot (status UNVERIFIED).
 *
 * @param id RFC 4122 UUID (v4).
 * @param slug URL-safe slug (lowercase, hyphenated).
 * @param type 
 * @param name 
 * @param description 
 * @param category 
 * @param status 
 * @param geometry 
 * @param lat Latitude in decimal degrees (WGS84 / EPSG:4326).
 * @param lng Longitude in decimal degrees (WGS84 / EPSG:4326).
 * @param address 
 * @param hours 
 * @param phone 
 * @param website 
 * @param amenities 
 * @param photos 
 * @param rating 
 * @param verification 
 * @param submittedBy 
 * @param createdAt RFC 3339 datetime in UTC.
 * @param updatedAt RFC 3339 datetime in UTC.
 */
@Serializable

data class SubmitSpotResponse (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* URL-safe slug (lowercase, hyphenated). */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: SpotType,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "category")
    val category: Category,

    @Contextual @SerialName(value = "status")
    val status: SpotStatus,

    @SerialName(value = "geometry")
    val geometry: SpotDetailGeometry,

    /* Latitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lat")
    val lat: java.math.BigDecimal?,

    /* Longitude in decimal degrees (WGS84 / EPSG:4326). */
    @Contextual @SerialName(value = "lng")
    val lng: java.math.BigDecimal?,

    @SerialName(value = "address")
    val address: kotlin.String?,

    @Contextual @SerialName(value = "hours")
    val hours: kotlin.Any? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String?,

    @Contextual @SerialName(value = "website")
    val website: java.net.URI?,

    @SerialName(value = "amenities")
    val amenities: kotlin.collections.List<Amenity>,

    @SerialName(value = "photos")
    val photos: kotlin.collections.List<SpotPhoto>,

    @SerialName(value = "rating")
    val rating: SpotRating,

    @SerialName(value = "verification")
    val verification: SpotVerification,

    @SerialName(value = "submittedBy")
    val submittedBy: SpotAuthor,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

