/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `PATCH /api/v1/me/dogs/:id`.
 *
 * @param name 
 * @param breed 
 * @param birthYear Year of birth (legacy, prefer birthDate).
 * @param birthDate Date of birth (YYYY-MM-DD).
 * @param photoUrl 
 * @param note 
 */
@Serializable

data class UpdateDogRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "breed")
    val breed: kotlin.String? = null,

    /* Year of birth (legacy, prefer birthDate). */
    @SerialName(value = "birthYear")
    val birthYear: kotlin.Int? = null,

    /* Date of birth (YYYY-MM-DD). */
    @Contextual @SerialName(value = "birthDate")
    val birthDate: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "photoUrl")
    val photoUrl: java.net.URI? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null

) {


}

