/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.GeoPoint
import nl.devrijehond.app.api.models.SubmitSpotRequestGeometry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for `PATCH /api/v1/me/spots/:id` (owner edit while UNVERIFIED).
 *
 * @param name 
 * @param description 
 * @param categoryId RFC 4122 UUID (v4).
 * @param amenityIds 
 * @param geometry 
 * @param point 
 * @param polygon 
 * @param address 
 * @param phone 
 * @param website 
 * @param hours 
 * @param photoUrls 
 */
@Serializable

data class UpdateSpotRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "categoryId")
    val categoryId: java.util.UUID? = null,

    @SerialName(value = "amenityIds")
    val amenityIds: kotlin.collections.List<@Contextual java.util.UUID>? = null,

    @SerialName(value = "geometry")
    val geometry: SubmitSpotRequestGeometry? = null,

    @SerialName(value = "point")
    val point: GeoPoint? = null,

    @SerialName(value = "polygon")
    val polygon: kotlin.collections.List<GeoPoint>? = null,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    @Contextual @SerialName(value = "website")
    val website: java.net.URI? = null,

    @Contextual @SerialName(value = "hours")
    val hours: kotlin.Any? = null,

    @SerialName(value = "photoUrls")
    val photoUrls: kotlin.collections.List<@Contextual java.net.URI>? = null

) {


}

