/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Result of an image upload.
 *
 * @param publicUrl Public CloudFront URL of the stored image.
 * @param key S3 object key of the stored image.
 */
@Serializable

data class UploadResponse (

    /* Public CloudFront URL of the stored image. */
    @Contextual @SerialName(value = "publicUrl")
    val publicUrl: java.net.URI,

    /* S3 object key of the stored image. */
    @SerialName(value = "key")
    val key: kotlin.String

) {


}

