/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.Vote

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Result of casting a verification vote.
 *
 * @param vote 
 * @param netScore Spot net weighted score after this vote.
 * @param confirmCount 
 * @param denyCount 
 * @param status Spot status after recompute (may flip to VERIFIED / HIDDEN).
 */
@Serializable

data class VoteResponse (

    @SerialName(value = "vote")
    val vote: Vote,

    /* Spot net weighted score after this vote. */
    @Contextual @SerialName(value = "netScore")
    val netScore: java.math.BigDecimal,

    @SerialName(value = "confirmCount")
    val confirmCount: kotlin.Int,

    @SerialName(value = "denyCount")
    val denyCount: kotlin.Int,

    /* Spot status after recompute (may flip to VERIFIED / HIDDEN). */
    @SerialName(value = "status")
    val status: kotlin.String

) {


}

