/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package nl.devrijehond.app.api.models

import nl.devrijehond.app.api.models.VoteValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The signed-in user's vote on a spot.
 *
 * @param id RFC 4122 UUID (v4).
 * @param spotId RFC 4122 UUID (v4).
 * @param `value` 
 * @param proximityVerified 
 * @param createdAt RFC 3339 datetime in UTC.
 */
@Serializable

data class Vote (

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* RFC 4122 UUID (v4). */
    @Contextual @SerialName(value = "spotId")
    val spotId: java.util.UUID,

    @Contextual @SerialName(value = "value")
    val `value`: VoteValue,

    @SerialName(value = "proximityVerified")
    val proximityVerified: kotlin.Boolean,

    /* RFC 3339 datetime in UTC. */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

